### ISSUE TITLE
Examples not working as described

### ISSUE THREAD

**Issue by dmushkov** [strimzi/strimzi-kafka-oauth#183] opened 2023-02-23 10:25 UTC
Hello, I'm trying examples docker follow steps described in readme authz

containers are started ok.
command 
```
bin/kafka-console-producer.sh --broker-list kafka:9092 --topic x_messages \
  --producer.config ~/team-a-client.properties
Message 1

```
[2023-02-23 10:18:05,999] DEBUG Authorization GRANTED - cluster: my-cluster, user: OAuthKafkaPrincipal(User:service-account-team-a-client, groups: null, session: 1701005620, token: eyJh**noWw), operation: DESCRIBE, resource: TOPIC:x_messages
kafka            | Granted scopes for resource (TOPIC:x_*): [WRITE, DESCRIBE] (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer.grant)
kafka-cli        | org.apache.kafka.common.KafkaException: Cannot execute transactional method because we are in an error state
kafka-cli        |      at org.apache.kafka.clients.producer.internals.TransactionManager.maybeFailWithError(TransactionManager.java:1125)
kafka-cli        |      at org.apache.kafka.clients.producer.internals.TransactionManager.maybeAddPartition(TransactionManager.java:442)
kafka-cli        |      at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:998)
kafka-cli        |      at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:912)
kafka-cli        |      at kafka.tools.ConsoleProducer$.send(ConsoleProducer.scala:70)
kafka-cli        |      at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:52)
kafka-cli        |      at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
kafka-cli        | Caused by: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
kafka-cli        | [2023-02-23 10:18:06,067] ERROR [Producer clientId=console-producer] Aborting producer batches due to fatal error (org.apache.kafka.clients.producer.internals.Sender)
kafka-cli        | org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
kafka-cli        | [2023-02-23 10:18:06,072] ERROR Error when sending message to topic x_messages with key: null, value: 1 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
kafka-cli        | org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
kafka            | [2023-02-23 10:18:06,175] DEBUG [SocketServer listenerType=ZK_BROKER, nodeId=1] Connection with /172.24.0.2 (channelId=172.24.0.5:9092-172.24.0.2:45054-7) disconnected (org.apache.kafka.common.network.Selector)
kafka            | java.io.EOFException
kafka            |      at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97)
kafka            |      at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
kafka            |      at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
kafka            |      at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
kafka            |      at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
kafka            |      at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
kafka            |      at kafka.network.Processor.poll(SocketServer.scala:1144)
kafka            |      at kafka.network.Processor.run(SocketServer.scala:1047)
kafka            |      at java.base/java.lang.Thread.run(Thread.java:829)
kafka            | [2023-02-23 10:18:06,175] DEBUG [SocketServer listenerType=ZK_BROKER, nodeId=1] Connection with /172.24.0.2 (channelId=172.24.0.5:9092-172.24.0.2:45050-6) disconnected (org.apache.kafka.common.network.Selector)
kafka            | java.io.EOFException
kafka            |      at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97)
kafka            |      at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
kafka            |      at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
kafka            |      at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
kafka            |      at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
kafka            |      at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
kafka            |      at kafka.network.Processor.poll(SocketServer.scala:1144)
kafka            |      at kafka.network.Processor.run(SocketServer.scala:1047)
kafka            |      at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by scholzj** [comment] 2023-02-23 10:32
@mstruk Any idea?

**Comment by mstruk** [comment] 2023-02-23 11:14
Nothing obvious based on this. Maybe instructions in README-authz.md no longer work.
I'd have to give it a try myself.

The only thing I can think about is that maybe IdempotentWrite permission is missing.

@dmushkov Can you specify the exact steps you perform, to reproduce the issue?

**Comment by dmushkov** [comment] 2023-02-23 11:21
hello @mstruk 
I start step by step as described in README-authz.md

basically it is visible in kafka some errors with permissions 
when I connect with cli producer

DEBUG Saving non-null grants for token: eyJh**NoXg (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer)
2023-02-23 13:20:01 [2023-02-23 11:20:01,396] DEBUG Authorization grants for user OAuthKafkaPrincipal(User:service-account-team-a-client, groups: null, session: 442195197, token: eyJh**NoXg): [{"scopes":["Describe","Read"],"rsid":"4aa7e032-1d3b-4966-aac2-6936d603836d","rsname":"Group:a_*"},{"scopes":["Describe","Read","Delete","Write","Alter","Create","DescribeConfigs","AlterConfigs"],"rsid":"59da8560-ef1a-4007-904c-323c27b9a4be","rsname":"Topic:a_*"},{"scopes":["Describe","Write"],"rsid":"ae0bb7b1-9f07-43b0-9516-1efd43958eb9","rsname":"Topic:x_*"}] (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer)
2023-02-23 13:20:01 [2023-02-23 11:20:01,411] DEBUG Authorization grants for user OAuthKafkaPrincipal(User:service-account-team-a-client, groups: null, session: 442195197, token: eyJh**NoXg): [{"scopes":["Describe","Read"],"rsid":"4aa7e032-1d3b-4966-aac2-6936d603836d","rsname":"Group:a_*"},{"scopes":["Describe","Read","Delete","Write","Alter","Create","DescribeConfigs","AlterConfigs"],"rsid":"59da8560-ef1a-4007-904c-323c27b9a4be","rsname":"Topic:a_*"},{"scopes":["Describe","Write"],"rsid":"ae0bb7b1-9f07-43b0-9516-1efd43958eb9","rsname":"Topic:x_*"}] (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer)
2023-02-23 13:20:01 [2023-02-23 11:20:01,413] DEBUG Authorization DENIED by ACL - user: OAuthKafkaPrincipal(User:service-account-team-a-client, groups: null, session: 442195197, token: eyJh**NoXg), operation: IDEMPOTENT_WRITE, resource: CLUSTER:kafka-cluster (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer)
2023-02-23 13:20:01 [2023-02-23 11:20:01,413] DEBUG Authorization grants for user OAuthKafkaPrincipal(User:service-account-team-a-client, groups: null, session: 442195197, token: eyJh**NoXg): [{"scopes":["Describe","Read"],"rsid":"4aa7e032-1d3b-4966-aac2-6936d603836d","rsname":"Group:a_*"},{"scopes":["Describe","Read","Delete","Write","Alter","Create","DescribeConfigs","AlterConfigs"],"rsid":"59da8560-ef1a-4007-904c-323c27b9a4be","rsname":"Topic:a_*"},{"scopes":["Describe","Write"],"rsid":"ae0bb7b1-9f07-43b0-9516-1efd43958eb9","rsname":"Topic:x_*"}] (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer)
2023-02-23 13:20:01 [2023-02-23 11:20:01,414] DEBUG Authorization DENIED by ACL - user: OAuthKafkaPrincipal(User:service-account-team-a-client, groups: null, session: 442195197, token: eyJh**NoXg), operation: WRITE, resource: TOPIC:hardcode (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer)

**Comment by mstruk** [comment] 2023-02-23 11:29
Yeah, it's the IDEMPOTENT_WRITE permission that's missing for this user. But it may be on purpose as part of the example.

Which is the first step in the README-authz.md example that behaves differently that expected?

**Comment by dmushkov** [comment] 2023-02-23 11:39
this line is producing error 
 
```
bin/kafka-console-producer.sh --broker-list kafka:9092 --topic a_messages \
  --producer.config ~/team-a-client.properties
First message
Second message
```

**Comment by mstruk** [comment] 2023-02-24 18:54
It looks like the example `kafka-authz-realm.json` is out of date.

Try replacing `examples/docker/keycloak-import/realms/kafka-authz-realm.json` with [this one](https://github.com/strimzi/strimzi-kafka-oauth/blob/main/testsuite/docker/keycloak/realms/kafka-authz-realm.json) from the testsuite.

**Comment by mstruk** [comment] 2023-03-07 17:39
Should be fixed in: https://github.com/strimzi/strimzi-kafka-oauth/pull/187

**Comment by dmushkov** [comment] 2023-03-08 08:42
Thank you very much!

**Closed** 2023-03-08 08:43 UTC
